# Generated by Django 3.1.3 on 2020-11-24 08:55

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_timeruser_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeruser',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, null=True),
        ),
    ]
