# Generated by Django 3.1.3 on 2020-11-24 09:02

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_timeruser_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeruser',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Canada/Mountain'),
        ),
    ]
