# Generated by Django 3.1.3 on 2020-11-17 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('tracker', '0001_initial'), ('tracker', '0002_auto_20201117_0850'), ('tracker', '0003_auto_20201117_0907'), ('tracker', '0004_auto_20201117_0910'), ('tracker', '0005_auto_20201117_0912'), ('tracker', '0006_auto_20201117_0915'), ('tracker', '0007_auto_20201117_0917')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('stop_timestamp', models.DateTimeField(blank=True, null=True)),
                ('run_seconds', models.IntegerField(default=0)),
                ('pause_seconds', models.IntegerField(default=0)),
                ('pause_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.activity')),
            ],
        ),
    ]
