# Generated by Django 3.1.3 on 2020-11-17 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20201117_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='pause_time',
            new_name='last_state_change_time',
        ),
    ]
