# Generated by Django 3.1.3 on 2020-11-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20201119_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='last_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
