# Generated by Django 3.1.3 on 2020-11-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20201119_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='is_tamper_proof',
            field=models.BooleanField(default=False),
        ),
    ]
