# Generated by Django 3.1.3 on 2020-11-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_timer_is_tamper_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='pause_seconds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='timer',
            name='run_seconds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
